### PR TITLE
Clean up book

### LINKED ISSUE #41: All link to the doc in the book are broken
For example: https://actix.rs/book/actix

- https://actix.rs/book/actix/trait.Actor.html
- https://actix.rs/book/actix/trait.Handler.html
- https://actix.rs/book/actix/trait.Message.html

etc...

### PR DESCRIPTION
**Pull request by JohnTitor**
- Check links by mdbook-linkcheck
- Move to GHA from Travis
- Fix links

Fixes #41

### CODE REVIEW

**Comment by JohnTitor** [comment]
Deployment: https://johntitor.github.io/book/actix/

**Review by jwdeitch — APPROVED** [review]

**Review by robjtede — APPROVED** [review]

**Comment by robjtede** [comment]
All pretty harmless.
What's the story with this change, out of interest?
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

**Comment by JohnTitor** [comment]
> What's the story with this change, out of interest?

I thought it'd be nicer to sync with the command displayed on https://rustup.rs.

**Comment by robjtede** [comment]
Ahh fair, wasn't aware they'd changed it there.

**Pull request merged**
